version: '3'

services:
  api-notifications:
    build: ./api-notifications
    container_name: api-notifications
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - "3000:3000"
    volumes:
      - ./api-notifications:/home/node/app
    depends_on:
      - mysql
      - redis
    environment:
      MYSQL_HOST: host.docker.internal
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: node_pubsub
      REDIS_HOST: host.docker.internal
      REDIS_PORT: 6379

  api-subscribers:
    build: ./api-subscribers
    container_name: api-subscribers
    entrypoint: ./.docker/entrypoint.sh
    volumes:
      - ./api-subscribers:/home/node/app
    depends_on:
      - mysql
      - redis
    environment:
      MYSQL_HOST: host.docker.internal
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: node_pubsub
      REDIS_HOST: host.docker.internal
      REDIS_PORT: 6379

  redis:
    image: redis:7.0.7-alpine3.17
    container_name: redis
    network_mode: bridge
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    network_mode: bridge
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: node_pubsub
      MYSQL_ROOT_PASSWORD: root

